orbs:
  node: circleci/node@4.1.0

commands:
  install-packages:
    parameters:
      cache-tag:
        default: build
        type: string
    steps:
      - node/install-packages:
          cache-version: <<parameters.cache-tag>>-{{ checksum "yarn.lock" }}
          include-branch-in-cache-key: true
          cache-path: ~/project/node_modules
          override-ci-command: yarn install --frozen-lockfile
          pkg-manager: yarn

version: 2.1
jobs:
  tests:
    executor:
      name: node/default
      tag: 15.5.1
    steps:
      - checkout
      - run:
          name: Install Node Sass
          command: yarn config set sass-binary-site https://npm.taobao.org/mirrors/node-sass
      - install-packages:
          cache-tag: unit-test
      - run:
          name: Run Unit Test
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: npm run test:coverage -- -w=2
      - store_artifacts:
          path: coverage
workflows:
  development-workflow:
    jobs:
      - tests
